spring.application.name=expense-tracker

spring.datasource.url=jdbc:mysql://localhost:3306/Expense_Tracker
spring.datasource.username=root
spring.datasource.password=root

# it is use  to read schema and data sql file it always. it is  never by default
# spring.sql.init.mode=always

# after work findished
spring.sql.init.mode=never

# when u dont have sql then also things can be done by this
# spring.sql.init.mode=embedded

#properties are for it:-->>>> create, createDrop, update, validate, none,create-only, truncate, drop
# validate, none --->> use in production
# update ---->>>> dev
#othere are fro testing
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql = true

#create -->>> first drop and then create at start time
#create-drop ---->>>>  first drop and then create at start time
#validate --->> it cheks the instance varibale and table coumn name,, it checks type as well
#update -->> if not thre then create if there then update if we add some values and it does not drop when app end